### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by SolitudeSF** [Aaahh/xwinwrap-tmp#4]
This program seems feature complete and stable and i would want to package it, so maybe you could add a version tag?

**Comment by mmhobi7** [comment]
https://github.com/Aaahh/xwinwrap/releases/tag/v0.9

**Comment by SolitudeSF** [comment]
thanks!

**Comment by mmhobi7** [comment]
I just want to let you know it has some issues still: https://github.com/Aaahh/xwinwrap/issues?q=is%3Aopen+is%3Aissue
