### ISSUE TITLE
xwinwrap will draw at top of any fullscreen window

### ISSUE THREAD

**Issue by ltsdw** [Aaahh/xwinwrap-tmp#9]
I didn't tested with any other WM besides dwm.

step to reproduce:

- run it on any terminal while in fullscreen

```
xwinwrap -b -s -fs -st -sp -nf -ov -fdt -- mpv -wid WID --really-quiet --framedrop=vo --no-audio /path/to/your/video
```

if isn't the terminal that is fullscreen it will draw on any other window that is fullscreen.

I think that it's how WID it's been get, it seems to get the id of any window covers the entire screen.

(if there isn't any fullscreen window it will draw normally at the background/root)

**Comment by mmhobi7** [comment]
Try
https://github.com/jarcode-foss/glava
If that can draw on the background correctly I can clone the window
functionality

**Comment by ltsdw** [comment]
sorry, how should I run it? like this?

```
xwinwrap -b -s -fs -st -sp -nf -ov -fdt -- glava
```

or should I run glava itself?

**Comment by mmhobi7** [comment]
By itself

**Comment by ltsdw** [comment]
well, by itself it creates another window.

and when running it with --desktop, it still creates another window also the output shows:

> No presets for current desktop environment ("dwm"), using default presets for embedding

**Comment by ltsdw** [comment]
Ok, apparently dwm didn't implements _NET_WM_WINDOW_TYPE_DESKTOP, already corrected that, so, yeah, glava does draw it correctly even when there's any fullscreen window. Well, kinda. (a """phantom""" idk how explain, of the terminal that it was spawned will follow at the background, it doesn't happens when spawned with dmenu)

still xwinwrap will draw on any fullscreen window that it finds.

but yeah, I would say that glava is drawing it correctly.

**Comment by ltsdw** [comment]
No, wait, after killing Xorg and restarting it, xwinwrap apparently started drawing at the root window as glava.

I will let this issue opened a little bit to test more, will close if it not happens again.

EDIT:

I discovered why it did drew 'correctly', was because I had glava running at background and forgot about it, so xwinwrap drew a top of glava, that's why I thought it was drawing correctly.

so to put altogether, glava draws at root correctly no matter if there's any fullscreen window or not.
xwinwrap still drawing above any fullscreen window it finds.

**Comment by ltsdw** [comment]
@mmhobi7 friendly ping :)

any update on this?

**Comment by exkc** [comment]
dwm will treat any panel or desktop widget as normal window(so it will tie them) by default when you use any any panel or desktop widget dwm.However i get it fix by using a custom patch call dontmanage.

This patch basically are add type of windows call the dontmanage that type of windows will be unmange by dwm which you can specify which windows belong to this type of windows in config.h. 

 However, This had a serious issue where when you restart dwm via restartsig patch , the unmangered windows wiil be above (cover) all the windows.Luckly there are work around for that : i add few line of code to make  dwm pull that unmangered windows above or below all the windows.you can config which windows you want dwm put it above or below all the windows .For example : you can config your panel above all the windows , you can config your desktop icon below all the windows.

**Comment by exkc** [comment]
Here is my dwm : https://gitlab.com/exkc/dwm-exkc

if you want the dontmanage patch , you can extract it from my dwm.However , I won't teach you how to extract it or help you to extract it .

**Comment by exkc** [comment]
After some research, I find a better patch for dwm that better than my one.(https://www.reddit.com/r/suckless/comments/pyhx5d/dwm_desktop_window_implementation/)

**Comment by ltsdw** [comment]
Thank you, I didn't know about the unmanaged patch, so I have a question maybe you know the answer, what is the window class hint for the xwinwrap? I tried looking in the xwinwrap's code but didn't find any, but found out that in fact xwinwrap hints the window with `_NET_WM_WINDOW_TYPE_DESKTOP` with the `-fdt` flag. The strange part it's seem to be ignored (I have the dwm-desktop_icons patch and it works for the glava).

**Comment by ltsdw** [comment]
Oh, never mind, dropped all the other flags and used only `-fs` and `-fdt` now it's working as it should. Closing.

**Comment by exkc** [comment]
Well, i dont use xwinwrap. xwinwrap say it is _NET_WM_WINDOW_TYPE_DESKTOP  so it should be _NET_WM_WINDOW_TYPE_DESKTOP  .
